package com.deepika.date_field_testing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestPojoClass implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public TestPojoClass() {
    }




}